package viettel.telecom.backend.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import viettel.telecom.backend.entity.promptbuilder.Template;
import viettel.telecom.backend.service.llm.LLMService;
import viettel.telecom.backend.service.promptbuilder.TemplateService;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/ai")
public class AIModelController {

    private final LLMService llmService;
    private final TemplateService templateService;

    @Autowired
    public AIModelController(LLMService llmService, TemplateService templateService) {
        this.llmService = llmService;
        this.templateService = templateService;
    }

    @PostMapping("/generate")
    public ResponseEntity<Map<String, Object>> generateResponse(
            @RequestParam String modelType,
            @RequestParam String templateId,
            @RequestBody Map<String, Object> userInput) {

        // Step 1: Fetch the system prompt from TemplateService
        String systemPrompt = templateService.getTemplate(templateId)
                .getSystemPrompt(); // Throws TemplateNotFoundException if not found

        // Step 2: Extract the user input message from the request body
        String userMessage = (String) userInput.get("message");

        // Step 3: Extract optional configuration from the request body
        Map<String, Object> config = (Map<String, Object>) userInput.getOrDefault("config", Map.of());

        // Step 4: Process the request using LLMService
        Map<String, Object> response = llmService.processRequest(modelType, systemPrompt, userMessage, config);

        // Step 5: Return the response
        return ResponseEntity.ok(response);
    }

    @PostMapping("/preview")
    public ResponseEntity<Map<String, Object>> generatePreview(@RequestBody Map<String, Object> request) {
        try {
            // Extract data from request
            String modelType = (String) request.get("modelType");
            String templateId = (String) request.get("templateId");
            String message = (String) request.get("message");
            Map<String, Object> config = (Map<String, Object>) request.getOrDefault("config", Map.of());

            // Fetch template details using TemplateService
            Template template = templateService.getTemplate(templateId);
            String systemPrompt = template.getSystemPrompt();

            // Combine systemPrompt and message for preview
            String combinedPrompt = systemPrompt + "\n" + message;

            // Use LLMService to generate response
            Map<String, Object> response = llmService.processRequest(modelType, combinedPrompt, message, config);

            // Extract the response content from the choices array
            String aiResponse = null;
            if (response != null && response.get("choices") != null) {
                List<Map<String, Object>> choices = (List<Map<String, Object>>) response.get("choices");
                if (choices != null && !choices.isEmpty()) {
                    Map<String, Object> messageContent = (Map<String, Object>) choices.get(0).get("message");
                    aiResponse = (String) messageContent.get("content");
                }
            }

            // Handle case where no content is available
            if (aiResponse == null) {
                aiResponse = "No response generated by the AI model.";
            }

            // Construct and return the preview response
            Map<String, Object> result = Map.of(
                    "combinedPrompt", combinedPrompt,
                    "response", aiResponse
            );

            return ResponseEntity.ok(result);

        } catch (Exception e) {
            e.printStackTrace(); // Log full stack trace for debugging
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("error", e.getMessage()));
        }
    }




}
